version: '3.8'

services:
  apigateway:
    build:
      context: ./ApiGateway  # ✅ Fix build context to match your project structure
      dockerfile: Dockerfile  # ✅ Make sure this is the correct Dockerfile name
    ports:
      - "5000:80"
    depends_on:
      - usermanagement
    networks:
      - backend

  usermanagement:
    build:
      context: ./UserManagement  # ✅ Fix build context to match your project structure
      dockerfile: Dockerfile      # ✅ Ensure this points to the correct Dockerfile
    ports:
      - "5001:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
