global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'tweet manager'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5002'] 

  - job_name: 'user manager'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:5001']
