name: API Gateway CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore ./APIGateway/APIGateway.csproj

      - name: Build API Gateway
        run: dotnet build ./APIGateway/APIGateway.csproj --no-restore

      - name: Test API Gateway (optional)
        run: |
          cd APIGateway
          dotnet test --no-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd APIGateway
          docker build -t $DOCKER_USERNAME/apigateway:latest .
          docker push $DOCKER_USERNAME/apigateway:latest
