name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Restore dependencies
      #   run: dotnet restore
      - name: Restore dependencies (only needed projects)
        run: dotnet restore ./KafkaTweetConsumer/KafkaTweetConsumer.csproj.nuget.dgspecs


      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          if [[ -z "$DOCKER_USERNAME" || -z "$DOCKER_PASSWORD" ]]; then
            echo "🚨 ERROR: Missing Docker credentials!"
            exit 1
          fi
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Verify Docker Hub Login
        run: docker info


      - name: Build and Push API Gateway Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd APIGateway  # ✅ Navigate to APIGateway directory
          docker build -t $DOCKER_USERNAME/apigateway:latest .
          docker push $DOCKER_USERNAME/apigateway:latest

      - name: Build and Push User Management Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd UserManagement  # ✅ Navigate to UserManagement directory
          docker build -t $DOCKER_USERNAME/usermanagement:latest .
          docker push $DOCKER_USERNAME/usermanagement:latest

