name: Tweet Management CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore ./TweetManagement/TweetManagement.csproj

      - name: Build TweetManagement
        run: dotnet build ./TweetManagement/TweetManagement.csproj --no-restore

      - name: Test (if needed)
        run: |
          cd Services/TweetManagement
          dotnet test --no-build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build & Push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd Services/TweetManagement
          docker build -t $DOCKER_USERNAME/tweetmanagement:latest .
          docker push $DOCKER_USERNAME/tweetmanagement:latest
